#+title: API Specification
#+weight: 1
#+hugo_cascade_type: docs
#+math: true

The client is going to interact with the game by sendin HTTP requests to the server. Those requests are going to be returned with a JSON response. All the possible actions a player can do are going to be done through the API. He can get informations about the state of the game like the ranking of the best players or do actions like building units and attacking another player.

Here is a list of all the possible HTTP requests a player can do, not including the authentification specific routes.

For all of these endpoints the user must have a valid =session_id= cookie, except GET /game/ranking which is a public ranking.

*** GET /
Take no parameter and return a welcome message containing the number of players registered.

#+begin_src json
  [
      "Welcome to my game which currently has 2 players !"
  ]
#+end_src

*** GET /game/ranking
Take no parameter and return all the players ranked by the amount of gold they have.

#+begin_src json
[
    [
        {
            "username": "user1",
            "gold": 4110
        },
        {
            "username": "user2",
            "gold": 222
        }
    ]
]
#+end_src

*** GET /game/village
Take no paramater and return the village informations of the connected player
#+begin_src json
[
    {
        "id": 31,
        "name": "testoo",
        "x_position": 50,
        "y_position": 96,
        "gold": 4110,
        "level": 1,
        "space_capacity": 5,
        "player_id": 43,
        "army_id": 21
    }
]
#+end_src

*** POST /game/create_building
#+begin_src json
  {
      "success": true
  }
#+end_src

*** POST /game/upgrade_building

*** POST /game/buy_units

*** POST /game/attack
