** Code styles
*** Style guide
**** fmt
First it is important to know that Zig comes with a formatter that you can use using:
#+begin_src shell
zig fmt file.zig
#+end_src
This util is going to enforce basic things for you like:
- Indentation
- Braces alignment
- Line length
- ....
**** Naming conventions
1. TitleCaseTypeName: for types and structs that are callable (for "classes" in other languages basically)
2. camelCaseFunctionName: for functions
3. snake\_case\_variable_name: for variables and everything else TODO formatter le snake_case_... car sur le web ca affiche pas comme il faut

*** undefined and null values
TODO for some reason the 2 org block code are not working, maybe i should "testsuite"
TODO how can i make the second one print the error ?

In Zig you can leave variables uninitialized, but you have to do that explicitly contrary to C where you can leave variables uninitialized and never truly notice it. Note that leaving the value undefined is going to leave the memory of this variable to some complete nonsense value (except in Debug mode where it will be [[https://github.com/ziglang/zig/issues/15603
][set to 0xaa]])
#+begin_src zig :imports '(std) :main 'yes :testsuite 'no
const my_var: u8 = undefined;
std.debug.print("my_var: {}\n", .{my_var});
#+end_src

This is to be avoided as much as possible, if you have some in your code it might makes sense to use an Optional type instead so that compiler can scream at you :)
#+begin_src zig :imports '(std) :main 'yes :testsuite 'no
const my_var: ?u8 = null;

// .? is syntaxic sugar for "orelse unreachable" which is going
// unreachable is going to emit a panic (unable to unwrapp null) !
// THIS CODE WILL PANIC IF UNCOMMENTED
// _ = my_var.?;

// if value is "null" then "42" will be assigned
const value: u8 = my_var orelse 42;

// print 42 because value was null before
std.debug.print("my_var = {}\n", .{value});
#+end_src

#+RESULTS:

*** Zen
Zig encourages you to use the Zen philosophy, I find them quite interesting to have in mind when coding, here they are:
- Communicate intent precisely.
- Edge cases matter.
- Favor reading code over writing code.
- Only one obvious way to do things.
- Runtime crashes are better than bugs.
- Compile errors are better than runtime crashes.
- Incremental improvements.
- Avoid local maximums.
- Reduce the amount one must remember.
- Focus on code rather than style.
- Resource allocation may fail; resource deallocation must succeed.
- Memory is a resource.
- Together we serve the users.

Sources:
https://ziglang.org/documentation/master/#Type-Coercion-undefined
https://nathancraddock.com/blog/zig-naming-conventions/o
https://ziglang.org/documentation/master/#undefined
https://ziglang.org/documentation/master/#Style-Guide
https://github.com/ziglang/zig/blob/master/lib/std/fmt.zig
